In [2]:
import numpy as np

<font size="3"> Arrays from list </font>

In [3]:
a_list = [1.5,2.4,3.5,4]
an_array = np.array(a_list, dtype='int64') # we can mention the datatype within the array 

In [4]:
# forming a multidimnesional array 
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<font size="3"> Creating arrays from Scratch </font>

In [5]:
# creating arrays of zeros 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# array of ones 
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# craete a 3x5 array filled with pi vals 
np.full((3,5), 3.15)

array([[3.15, 3.15, 3.15, 3.15, 3.15],
       [3.15, 3.15, 3.15, 3.15, 3.15],
       [3.15, 3.15, 3.15, 3.15, 3.15]])

In [8]:
# create an array filled with a sequence starting 0 end at 20
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# create an array of five values evenly spaced between 0 and 1 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# creating 3x3 random array between 0 and 1
np.random.random((3,3))

array([[0.67142545, 0.85423444, 0.12108823],
       [0.19665378, 0.76475328, 0.50126136],
       [0.948063  , 0.25521264, 0.34076779]])

In [11]:
# creating a 3X3 array of normally distributed ranodm values 
np.random.normal(0,1,(3,3))

array([[-0.23643041, -0.44932941,  0.69782719],
       [ 0.05044222,  0.02843184, -1.39274399],
       [-0.02872017, -0.21715791,  1.62770627]])

In [12]:
# creating a 3x3 array of random integers in interval of [0,10]
np.random.randint(0,10,(3,3))

array([[9, 2, 5],
       [2, 2, 2],
       [8, 7, 6]])

In [13]:
# 3X3 indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# create an uninitialized array of three integers, the values will be that already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [15]:
np.arange(2,10,2) # first represent the starting, 2nd ending (not involved by itself ) last represent number of steps

array([2, 4, 6, 8])

<font size="5"> Numpy array attributes </font>

In [16]:
np.random.seed(0) # seed for reproducibility of the same values

In [17]:
x1 = np.random.randint(10, size=6) # uni dimensional 
x2 = np.random.randint(10, size=(3,4)) # two dim 
x3 = np.random.randint(10, size=(3,4,5)) # 3 dim

Concatination of arrays

In [20]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [22]:
# np.concatenate function is called to conc to arrays, 
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [24]:
# it can be also used for two dim arrays
grid = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
# we can also specify the axis of concatenation
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
# we can use np.vstack or hstack options instead of concatenate and mentioning axis
x = np.array([9,8,7])
np.vstack([x,grid]) # the arrays are concatenated vertically 

array([[9, 8, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
x = np.array([[99],
             [99]])
np.hstack([x,grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

Splitting of arrays

In [33]:
# specifying the indexes of slpliting
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])
x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [37]:
# similarly we can spilt via vsplit or hsplit too
grid = np.arange(16).reshape((4,4))

# vertically spliting
uper, lower = np.split(grid,[2])
uper,lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [41]:
left,right = np.hsplit(grid,[2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))